DROP DATABASE 
CREATE DATABASE ANONIMO
USE ANONIMO 
CREATE TABLE LOGIN (
    id (255) VARCHAR NOT NULL;
    email (60) VARCHAR NOT NULL;
    password (40) VARCHAR UNIQUE NOT NULL;
);

CREATE TABLE REGISTRO (
    name (40) VARCHAR NOT NULL;
    email (60) VARCHAR NOT NULL;
    password (40) VARCHAR UNIQUE NOT NULL;
);

CREATE DATABASE USUARIOS_REGISTRADOS
USE USUARIOS_REGISTRADOS
CREATE TABLE GESTION_DE_PERFIL (
    actualizar_nombre (60) VARCHAR NOT NULL;
    actualizar_email (60) VARCHAR NOT NULL;
    actualizar_password (40) VARCHAR NOT NULL UNIQUE;
);

CREATE TABLE OPINION (
    VOTACION (255) VARCHAR NOT NULL;
);

CREATE TABLE VOTAR (
    VOTACION POSITIVA (255) VARCHAR NOT NULL; 
    VOTACION NEGATIVA (255) VARCHAR NOT NULL;
);